server:
  port: 8082
spring:
  application:
    name: "Tani Bilet"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/tani-bilet
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    username: app_user
    password: apppassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
