server:
  port: 8082
springdoc:
  api-docs:
    version: OPENAPI_3_0
spring:
  application:

    name: "Tani Bilet"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/tani-bilet
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    username: app_user
    password: apppassword
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: tani.biletio@gmail.com
    password: ${SMTP_PASSWORD:changeme}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
